# -*- coding: utf-8 -*-
"""PER 5. Program Multiple Inheritance Mahasiswa. 9

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qCEfbWnIx7YSmtOF7HtAnittDtST06Sk
"""

#Multilavel 5210411240 Rivaldi Kenny N 
class ComputerPart:
  def __init__(self, pabrikan, nama, harga) :
    self.pabrikan = pabrikan
    self.nama = nama
    self.harga = harga

class Processor(ComputerPart) :
  def __init__(self, pabrikan, nama, harga) :
    self.pabrikan = pabrikan
    self.nama = nama 
    self.harga = harga
        
  def Tampil(self) :
    print('1')
    print(f'Nama Merk             : {self.nama}')
    print(f'Diproduksi Oleh       : {self.pabrikan}')
    print(f'Dijual dengan harga   : {rupiah(self.harga)}')

class RandomAccessMemory(Processor) :
  def __init__(self, pabrikan, nama, harga) :
    self.pabrikan = pabrikan
    self.nama = nama 
    self.harga = harga

  def Tampil(self) :
    print('2')
    print(f'Merk                  : {self.pabrikan}')
    print(f'Spesifikasi           : {self.nama}')
    print(f'Dijual dengan harga   : {rupiah(self.harga)}')

class HardDiskSATA(RandomAccessMemory) :
  def __init__(self, pabrikan, nama, harga) :
    self.pabrikan = pabrikan
    self.nama = nama 
    self.harga = harga
  
  def Tampil(self) :
    print('3.')
    print(f'Merk                  : {self.pabrikan}')
    print(f'Spesifikasi           : {self.nama}')
    print(f'Dijual dengan harga   : {rupiah(self.harga)}')

p = Processor('Intel', 'Core i7 7740X', 4350000)   
ram = RandomAccessMemory('V-Gen', 'DDR4 SODimm PC19200/2400MHz', 328000)
hdd = HardDiskSATA('Seagate', 'HDD 2.5 inch', 295000)

parts = [p, ram, hdd] 
print("               PROGRAM MULTILEVEL COMPUTER PART")

for part in parts :
  print()
  part.Tampil()