# -*- coding: utf-8 -*-
"""per_5_program_Multiple_inheritance_ComputerPart_12

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qCEfbWnIx7YSmtOF7HtAnittDtST06Sk
"""

#program_Multiple_inheritance 5210411240 Rivaldi Kenny N
    
class ComputerPart1():
  def __init__(self, pabrikan, nama) :
    self.pabrikan = pabrikan
    self.nama = nama

class ComputerPart2() : 
  def __init__(self, harga) :
    self.harga = harga

class Processor(ComputerPart1, ComputerPart2) :
  def __init__(self, pabrikan, nama, harga) :
    ComputerPart1.__init__(self, pabrikan, nama)
    ComputerPart2.__init__(self, harga)
        
  def Tampil(self) :    
    print(f'Diproduksi oleh        :{self.pabrikan}')
    print(f'Nama barang            :{self.nama}')
    print(f"Dibandrol dengan harga : {rupiah(self.harga)}")

class RandomAccessMemory(ComputerPart1, ComputerPart2) :
  def __init__(self, pabrikan, nama, harga) :
    ComputerPart1.__init__(self, pabrikan, nama)
    ComputerPart2.__init__(self, harga)

  def Tampil(self) :    
    print(f'Diproduksi oleh        :{self.pabrikan}')
    print(f'Nama barang            :{self.nama}')
    print(f"Dibandrol dengan harga : {rupiah(self.harga)}")

class HardDiskSATA(ComputerPart1, ComputerPart2) :
  def __init__(self, pabrikan, nama, harga) :
    ComputerPart1.__init__(self, pabrikan, nama)
    ComputerPart2.__init__(self, harga)

  def Tampil(self) :    
    print(f'Diproduksi oleh        :{self.pabrikan}')
    print(f'Nama barang            :{self.nama}')
    print(f"Dibandrol dengan harga : {rupiah(self.harga)}")

p = Processor('Intel', "Core i7 7740X", 4350000)
ram = RandomAccessMemory('V-Gen', 'DDR4 SODimm PC19200/2400MHz', 328000)
hdd = HardDiskSATA('Seagate', 'HDD 2.5 inch', 295000)

parts = [p, ram, hdd]  
print("         PROGRAM MULTIPLE COMPUTER PART")
for part in parts :
  print()
  part.Tampil()
  print('------------------------------------------------------------------------')