# -*- coding: utf-8 -*-
"""PER_4_Latihan_1_sampai_7_5210411240_RIVALDI_KENNY_N_PBO_7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Dk1n9LdASYY1Uwkr4_HwwE60qGH4OAaH

LATIHAN 1
"""

class Hitung:
    def __init__(self):
        self. __angkaRahasia=0
        
    def tampilkanHitung(self):
        self. __angkaRahasia += 1
        print(self. __angkaRahasia)

hitungan=Hitung()
hitungan.tampilkanHitung()

"""LATIHAN 2"""

#semua variable bersifat publik

class Mobil():
    def __init__(self,jendela,pintu,mesin):
        self.jendela=jendela
        self.pintu=pintu
        self.mesin=mesin

audi=Mobil(4,5,"Diesel")
print(audi.jendela)
print(audi.pintu)
print(audi.mesin)

"""LATIHAN 3"""

class Utama:
    def __init__(self):
        self._a = 2
        
class Turunan(Utama):
    def __init__(self):
        #memanggil konstruktor pada kelas utama
        Utama.__init__(self)
        print("memanggil variable protected pada class utama:",self._a)
        
        #memeodifikasi protected variable:
        self._a = 3
        print("memanggil variable protected yang dimodifikasi diluar class",self._a)

objek1 = Turunan()
objek2 = Utama()

#memanggil variable protected
print("mengakses variable protected dari objek1: ",  objek1._a)
print("mengakses variable protected dari objek2: ", objek2._a)

"""LATIHAN 4"""

#semua variable bersifat protected

class Mobil():
    def __init__(self,jendela,pintu,mesin):
        self._jendela=jendela
        self._pintu=pintu
        self._mesin=mesin

class Truk(Mobil):
    def __init__(self,jendela,pintu,mesin,tipe):
        super().__init__(jendela,pintu,mesin)
        self.tipebak=tipe

truk=Truk(4,4,"Diesel","bak terbuka")
print(truk._mesin)
print(truk.tipebak)

"""LATIHAN 5"""

#fungsi private dan public

class Pegawai:
    __nama=""
    __alamat=""
    __gaji=0
    
    def __init__(self,nama,alamat):
        self.__nama=nama
        self.__alamat=alamat
        
    def __hitungGaji(self):
        upahLembur=20000
        gajiPokok=2000000
        jumLembur=int(input("total jam lembur: "))
        self.__gaji=(upahLembur*jumLembur)+gajiPokok
        
    def tampilDetail(self):
        print("\n--Menghitung dan Menampilkan Detail Gaji Pegawai--")
        print("Nama: ", self.__nama)
        print("Alamat: ", self.__alamat)
        self.__hitungGaji()
        print("Total Gaji: ", self.__gaji)
        
#membuat objek pegawai
pgw1=Pegawai("Mikasa Ackerman", "Wall Rose")
pgw1.tampilDetail()

pgw2=Pegawai("Saya Kisaragi", "prefektur Nagano")
pgw2.tampilDetail()

"""LATIHAN 6"""

class Segitiga:
    def __init__(self, alas, tinggi):
        self.alas = alas
        self.tinggi = tinggi
        self.luas = 0.5 * alas * tinggi
        
segitiga_besar = Segitiga(100,80)

#akses variable public: alas, tinggi, dan luas dari luar kelas segitiga
print("alas: ",segitiga_besar.alas)
print("tinggi: ",segitiga_besar.tinggi)
print("luas: ",segitiga_besar.luas)

"""LATIHAN 7"""

class Mobil():
    def __init__(self,jendela,pintu,mesin):
        self.__jendela=jendela
        self.__pintu=pintu
        self.__mesin=mesin
    
    def Tampil(self):
        print("Jendela :", self.__jendela)
        print("Pintu :", self.__pintu)
        print("Mesin :", self.__mesin)
        
audi=Mobil(4,2,"Diesel")
audi.Tampil()