# -*- coding: utf-8 -*-
"""per_5_program_hierarchical_inheritance_computerpart_11

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1607Ndy9TWXXZonbsp5lPtqcb2_n6rZ2p
"""

#Hierarchical_inheritance 5210411240 Rivaldi Kenny N

class ComputerPart:
  def __init__(self, pabrikan, nama, harga) :
    self.pabrikan = pabrikan
    self.nama = nama    
    self.harga = harga

class Processor(ComputerPart) :
  def __init__(self, pabrikan, nama, harga) :
    self.pabrikan = pabrikan
    self.nama = nama 
    self.harga = harga
        
  def Tampil(self) : 
    print(f'Merk  : {self.pabrikan}')
    print(f'Seri  : {self.nama}')
    print(f'Harga : {self.harga}')

class RandomAccessMemory(ComputerPart) :
  def __init__(self, pabrikan, nama, harga, kapasitas) :
    self.pabrikan = pabrikan
    self.nama = nama
    self.harga = harga
    self.kapasitas = kapasitas

  def Tampil(self) : 
    print(f'Diproduksi oleh : {self.pabrikan}')
    print('Spesifikasi : ')
    print(f'       -Jenis/Seri barang : {self.nama}')
    print(f'       -Kapasitas         : {self.kapasitas}')
    print(f'Dipatok dengan harga : {self.harga}')

class HardDiskSATA(ComputerPart) :
  def __init__(self, pabrikan, nama, harga, kapasitas, rpm) :
    self.pabrikan = pabrikan
    self.nama = nama 
    self.harga = harga
    self.kapasitas = kapasitas
    self.rpm = rpm

  def Tampil(self) :
    print(f' Diproduksi oleh  : {self.pabrikan}')
    print(f'Nama produk       : {self.nama} ')
    print(f'Spesifikasi :')
    print(f"        -Kapasitas : {self.kapasitas}")
    print(f"        -RPM : {self.rpm}")
    print(f"Dipatok dengan Harga : {self.harga}")

p = Processor('Intel', 'Core i7 7740X', 4350000)
ram = RandomAccessMemory('V-Gen', 'DDR4 SODimm PC19200/2400MHz', 328000, "4GB")
hdd = HardDiskSATA('Seagate', 'HDD 2.5 inch', 295000, '500GB', 7200)

parts = [p, ram, hdd]   
print("        PROGRAM HIERARCHIAL COMPUTER PART")

for part in parts :
  print()
  part.Tampil()
  print('-----------------------------------------------------------------------')